[build]
  functions = "netlify/functions"
  publish = "public"  # Assuming you have a public directory for static files

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
